/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RelacionDos;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Alberto
 */
public class PanelCentralBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelInferior
     */
    public PanelCentralBotones() {
        initComponents();
    }

    public JButton getBtn_inicio1() {
        return btn_inicio1;
    }

    public void setBtn_inicio1(JButton btn_inicio1) {
        this.btn_inicio1 = btn_inicio1;
    }

    public JButton getBtn_inicio2() {
        return btn_inicio2;
    }

    public void setBtn_inicio2(JButton btn_inicio2) {
        this.btn_inicio2 = btn_inicio2;
    }

    public JButton getBtn_inicio3() {
        return btn_inicio3;
    }

    public void setBtn_inicio3(JButton btn_inicio3) {
        this.btn_inicio3 = btn_inicio3;
    }

    public JButton getBtn_parar1() {
        return btn_parar1;
    }

    public void setBtn_parar1(JButton btn_parar1) {
        this.btn_parar1 = btn_parar1;
    }

    public JButton getBtn_parar2() {
        return btn_parar2;
    }

    public void setBtn_parar2(JButton btn_parar2) {
        this.btn_parar2 = btn_parar2;
    }

    public JButton getBtn_parar3() {
        return btn_parar3;
    }

    public void setBtn_parar3(JButton btn_parar3) {
        this.btn_parar3 = btn_parar3;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_inicio1 = new javax.swing.JButton();
        btn_inicio2 = new javax.swing.JButton();
        btn_inicio3 = new javax.swing.JButton();
        btn_parar1 = new javax.swing.JButton();
        btn_parar2 = new javax.swing.JButton();
        btn_parar3 = new javax.swing.JButton();

        btn_inicio1.setText("START 1");
        btn_inicio1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btn_inicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicio1ActionPerformed(evt);
            }
        });

        btn_inicio2.setText("START 2");
        btn_inicio2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        btn_inicio3.setText("START 3");
        btn_inicio3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        btn_parar1.setForeground(java.awt.Color.red);
        btn_parar1.setText("STOP 1");
        btn_parar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btn_parar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parar1ActionPerformed(evt);
            }
        });

        btn_parar2.setForeground(java.awt.Color.red);
        btn_parar2.setText("STOP 2");
        btn_parar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btn_parar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parar2ActionPerformed(evt);
            }
        });

        btn_parar3.setForeground(java.awt.Color.red);
        btn_parar3.setText("STOP 3");
        btn_parar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        btn_parar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_inicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_parar1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_parar2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(btn_inicio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_parar3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inicio3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_parar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_parar2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_parar3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_inicio1ActionPerformed

    private void btn_parar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_parar1ActionPerformed

    private void btn_parar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_parar2ActionPerformed

    private void btn_parar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_parar3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicio1;
    private javax.swing.JButton btn_inicio2;
    private javax.swing.JButton btn_inicio3;
    private javax.swing.JButton btn_parar1;
    private javax.swing.JButton btn_parar2;
    private javax.swing.JButton btn_parar3;
    // End of variables declaration//GEN-END:variables
}
